### ISSUE TITLE
rewrite the bot 

### ISSUE THREAD

**Issue by AKDev21** [AKDev21/GWGBot#22]
i would like to correct my mistake of "rewriting GWGBot in java just because i like java syntax" by rewriting to a language which has a good discord library

i'm open for suggestions from the GWG Community about which discord library you prefer with a reason "why"

i will consider your suggestion if there's a valid reason to use that particular discord library

goals for considering library
- fast( less memory usage, because there's 512 mb RAM limit on heroku )
- easy to use
- small in size

**Comment by AKDev21** [comment]
I won't even consider discord library written for the following langauges because the langauge is slow and uses more ram as compared to a compiled langauge:
python, javascript, Java, typescript, Scala, c#

I don't have experience with Go, Clojure, Crystal, Elixir, Julia, nim, php, swift so i don't know how much memory they consume

**Comment by AKDev21** [comment]
`D++` in c++, too verbose
`sleepy-discord` in c++, unactive
`discord-rs` in rust, unactive
`serenity` in rust, more verbose than D++( i would consider D++ instead of serenity )
`twilight` in rust, verbose, more verbose than D++
`coxir` in Elixer, unactive
`lacord` in Lua, unactive
`discordnim`: in Nim, unactive
`DiscordPHP` in PHP
`restcord` in PHP
`discordrb` in Ruby


Options to consider from
`Orca` in C, easy, fast
`discordpp` in c++
`discljord` in Clojure
`discordcr` in Crystal
`nyxx` in dart
`nostrum` in Elixer
`discordgo` in GO
`disgord` in GO
`Discord.jl` in Julia
`Discordia` in lua
`dimscord` in Nim

**Comment by Lioncat2002** [comment]
Bruh

**Comment by Lioncat2002** [comment]
Can we use python now?
It's the easiest imo
Especially enhanced-dpy https://github.com/iDevision/enhanced-discord.py
Fairly active fork of now dead discord.py

**Comment by Lioncat2002** [comment]
>  javascript, Java, typescript, Scala, python, Elixer, Ruby, C#
Actually most of the successful bots (like carl(dpy), Mee6(js)) are written in these languages :pain:
Compiled vs interpreted doesn't really play a major part in writing bots imho

**Comment by AKDev21** [comment]
> Can we use python now?

no, becuase a simple infinite loop in python uses 10 mb of memory and we only have 512 mb of memory

**Comment by AKDev21** [comment]
> Actually most of the successful bots (like carl(dpy), Mee6(js)) are written in these languages :pain:
Compiled vs interpreted doesn't really play a major part in writing bots imho

i don't have any problem in using any of the languages, but these languages are dynamic, so they use a lot of memory

**Comment by AKDev21** [comment]
> oh and u can host it on repl.it

( from discord )

repl.it is not consitent and i have experienced time out many times because of no reason
